# Generated by Django 6.0.3 on 2026-03-09 18:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=200)),
                ('normalized_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('operation_type', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('auto_created', models.BooleanField(db_index=True, default=False)),
                ('needs_review', models.BooleanField(db_index=True, default=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('total_jobs', models.IntegerField(default=0)),
                ('active_jobs', models.IntegerField(default=0)),
                ('last_job_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_mapping',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('normalized_title', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('company', models.CharField(db_index=True, max_length=200)),
                ('company_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('operation_type', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('job_category', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('sub_role', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(db_index=True, default='new', max_length=20)),
                ('source', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('senior_flag', models.BooleanField(db_index=True, default=False)),
                ('senior_override', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_senior_position', models.BooleanField(db_index=True, default=False)),
                ('posted_date', models.DateField(blank=True, db_index=True, null=True)),
                ('expiration_date', models.DateField(blank=True, db_index=True, null=True)),
                ('retrieved_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(db_index=True, max_length=1000, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('is_remote', models.BooleanField(default=False)),
                ('salary_visible', models.BooleanField(default=True)),
                ('license_required', models.BooleanField(default=False)),
                ('training_required', models.BooleanField(default=False)),
                ('on_job_training', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraper_posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'managed': True,
            },
        ),
    ]
