# Shared job schema for all scrapers
# Use this template to ensure all output dicts are consistent


def get_job_dict(
    title=None,
    company=None,
    url=None,
    description=None,
    normalized_title=None,
    company_id=None,
    country_code=None,
    location=None,
    operation_type=None,
    status=None,
    source=None,
    senior_flag=None,
    senior_override=None,
    is_senior_position=None,
    posted_date=None,
    retrieved_date=None,
    last_checked=None,
    last_updated=None,
    raw_json=None,
    salary_min=None,
    salary_max=None,
    salary_currency="USD",
    posted_by=None,
    created_at=None,
    updated_at=None,
    apply_url=None,
    job_type=None,
    department=None,
    requirements=None,
    qualifications=None,
    timestamp=None,
    job_id=None,
    job_post_id=None,
    contract_type=None,
    contract_duration=None,
    travel_required=None,
    shift_work=None,
    responsibilities=None,
    **extra_fields,
):
    base = {
        "title": title or "Unknown Title",
        "normalized_title": normalized_title
        or (title.lower().strip() if title else None),
        "company": company or "Unknown Company",
        "company_id": company_id,
        "country_code": country_code or "Unknown",
        "location": location or "Unknown",
        "operation_type": operation_type or None,
        "status": status or "new",
        "source": source or "Unknown",
        "senior_flag": senior_flag if senior_flag is not None else False,
        "senior_override": senior_override,
        "is_senior_position": is_senior_position
        if is_senior_position is not None
        else False,
        "posted_date": posted_date,
        "retrieved_date": retrieved_date,
        "last_checked": last_checked,
        "last_updated": last_updated,
        "url": url or "",
        "description": description or "No description provided.",
        "raw_json": raw_json,
        "salary_min": salary_min,
        "salary_max": salary_max,
        "salary_currency": salary_currency,
        "posted_by": posted_by,
        "created_at": created_at,
        "updated_at": updated_at,
        "apply_url": apply_url or url,
        "job_type": job_type or "Unknown",
        "department": department or "Unknown",
        "requirements": requirements or "Not specified",
        "qualifications": qualifications or "Not specified",
        "timestamp": timestamp,
        "job_post_id": job_post_id,
        "contract_type": contract_type or "Not specified",
        "contract_duration": contract_duration or "Not specified",
        "travel_required": travel_required or "Not specified",
        "shift_work": shift_work or "Not specified",
        "responsibilities": responsibilities or "Not specified",
        "job_id": job_id,
    }
    # Merge any extra fields provided by scraper without losing base keys
    base.update(extra_fields or {})
    return base
