# Generated by Django 5.2.8 on 2025-11-25 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraper_name', models.CharField(max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('max_jobs', models.IntegerField(blank=True, help_text='Maximum number of jobs to scrape (null = unlimited)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_pages', models.IntegerField(blank=True, help_text='Maximum number of pages to scrape (null = unlimited)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('timeout', models.IntegerField(default=300, help_text='Timeout in seconds')),
                ('retry_count', models.IntegerField(default=3, help_text='Number of retries on failure')),
                ('schedule_enabled', models.BooleanField(default=False)),
                ('schedule_cron', models.CharField(blank=True, help_text='Cron expression for scheduling (e.g., "0 */6 * * *")', max_length=100)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('total_runs', models.IntegerField(default=0)),
                ('successful_runs', models.IntegerField(default=0)),
                ('failed_runs', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scraper_name'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=1000, unique=True)),
                ('job_id', models.CharField(db_index=True, max_length=200)),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('first_scraped', models.DateTimeField(auto_now_add=True)),
                ('last_scraped', models.DateTimeField(auto_now=True)),
                ('scrape_count', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('job_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-last_scraped'],
                'indexes': [models.Index(fields=['source', 'is_active'], name='scraper_man_source_89f87f_idx'), models.Index(fields=['-last_scraped'], name='scraper_man_last_sc_4d836a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScraperJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraper_name', models.CharField(choices=[('signature', 'Signature Aviation'), ('flygosh', 'Flygosh Jobs'), ('aap', 'AAP Aviation'), ('aviationjobsearch', 'Aviation Job Search'), ('goose', 'GOOSE Recruitment'), ('all', 'All Scrapers')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds', null=True)),
                ('jobs_found', models.IntegerField(default=0)),
                ('jobs_new', models.IntegerField(default=0)),
                ('jobs_updated', models.IntegerField(default=0)),
                ('jobs_duplicate', models.IntegerField(default=0)),
                ('output_file', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('triggered_by', models.CharField(blank=True, max_length=100)),
                ('parameters', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='scraper_man_created_f9d645_idx'), models.Index(fields=['status'], name='scraper_man_status_7c4e70_idx'), models.Index(fields=['scraper_name'], name='scraper_man_scraper_1cc93b_idx')],
            },
        ),
    ]
