# Generated by Django 5.1.14 on 2025-12-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_manager', '0004_alter_scraperjob_scraper_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperjob',
            name='scraper_name',
            field=models.CharField(choices=[('signature', 'Signature Aviation'), ('flygosh', 'Flygosh Jobs'), ('aviationindeed', 'Aviation Indeed'), ('aap', 'AAP Aviation'), ('indigo', 'IndiGo Airlines'), ('aviationjobsearch', 'Aviation Job Search'), ('goose', 'GOOSE Recruitment'), ('linkedin', 'LinkedIn Jobs'), ('pilots_global', 'PilotsGlobal'), ('all', 'All Scrapers')], max_length=50),
        ),
    ]
