# Generated by Django 5.1.14 on 2025-12-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_manager', '0005_alter_scraperjob_scraper_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperjob',
            name='scraper_name',
            field=models.CharField(choices=[('aap', 'AAP Aviation'), ('airbus', 'Airbus Careers'), ('airindia', 'Air India Careers'), ('allflyingjobs', 'All Flying Jobs'), ('aviationcv', 'AviationCV'), ('aviationindeed', 'Aviation Indeed'), ('aviationjobsearch', 'Aviation Job Search'), ('boeing', 'Boeing Careers'), ('cargolux', 'Cargolux Careers'), ('emirates', 'Emirates Group Careers'), ('flygosh', 'Flygosh Jobs'), ('goose', 'GOOSE Recruitment'), ('indigo', 'IndiGo Airlines'), ('jsfirm', 'JSfirm'), ('linkedin', 'LinkedIn Jobs'), ('pilots_global', 'PilotsGlobal'), ('signature', 'Signature Aviation'), ('all', 'All Scrapers')], help_text='Select which scraper to run', max_length=50),
        ),
    ]
