# Generated by Django 5.2.8 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraper_manager", "0013_webhookconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scraperjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("retrying", "Retrying"),
                    ("cancelling", "Cancelling"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="scraperjob",
            name="attempt_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scraperjob",
            name="cancel_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scraperjob",
            name="failure_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="scraperjob",
            name="failure_context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scraperjob",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scraperjob",
            name="progress_message",
            field=models.CharField(
                blank=True, help_text="Latest progress detail", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="scraperjob",
            name="task_id",
            field=models.CharField(
                blank=True, db_index=True, help_text="Celery task ID", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="scraperjob",
            name="worker_name",
            field=models.CharField(
                blank=True, help_text="Worker hostname", max_length=255
            ),
        ),
    ]
